--- #YAML:1.0
name: Gestinanna-POF
version: 0.06
license: perl
distribution_type: module
requires:
  Class::Accessor: 0.17
  Class::Container: 0.07
  Class::Factory: 1
  Class::Fields: 0.14
  Class::Observable: 1.02
  NEXT: 0
  Params::Validate: 0.24
recommends:
  Alzabo: 0
  DBD::SQLite: 0
  DBI: 0
  MLDBM: 0
  MLDBM::Sync: 0
  Net::LDAP: 0
build_requires: {}
conflicts: {}
provides:
  Gestinanna::POF:
    file: lib/Gestinanna/POF.pm
    version: 0.06
  Gestinanna::POF::Alzabo:
    file: lib/Gestinanna/POF/Alzabo.pm
    version: 0.04
  Gestinanna::POF::Base:
    file: lib/Gestinanna/POF/Base.pm
    version: 0.02
  Gestinanna::POF::Container:
    file: lib/Gestinanna/POF/Container.pm
    version: 0.02
  Gestinanna::POF::Iterator:
    file: lib/Gestinanna/POF/Iterator.pm
  Gestinanna::POF::LDAP:
    file: lib/Gestinanna/POF/LDAP.pm
    version: 0.04
  Gestinanna::POF::Lock:
    file: lib/Gestinanna/POF/Lock.pm
  Gestinanna::POF::MLDBM:
    file: lib/Gestinanna/POF/MLDBM.pm
    version: 0.04
  Gestinanna::POF::Secure:
    file: lib/Gestinanna/POF/Secure.pm
    version: 0.02
  Gestinanna::POF::Secure::ReadOnly:
    file: lib/Gestinanna/POF/Secure/ReadOnly.pm
generated_by: Module::Build version 0.21
